language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-get install libopencv-dev
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
  - sudo ln /dev/null /dev/raw1394

script: ruby compare.rb