/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class SemiGlobalMatchingStorlet */

#ifndef _Included_SemiGlobalMatchingStorlet
#define _Included_SemiGlobalMatchingStorlet
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     SemiGlobalMatchingStorlet
 * Method:    process
 * Signature: ([B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_SemiGlobalMatchingStorlet_process
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
